### ISSUE TITLE
Backspace stuck right after non-decimal

### ISSUE THREAD

**Issue by approxit** [plentz/jquery-maskmoney#112]
After placing the cursor right after ```decimal``` char or ``` thousands``` char you can't simply use backspace to throw out some digits. Delete key works just fine.

Little example:
```1 234.56|``` => backspace key => ```123.45|``` Correct!
```1 234.|56``` => backspace key => ```1 234.|56``` Nothing?!
```1 |234.56``` => backspace key => ```1 |234.56``` Nothing?!

**Comment by plentz** [comment]
@approxit using the last source https://github.com/plentz/jquery-maskmoney/blob/master/src/jquery.maskMoney.js the problem still exists? I'm unable to reproduce it :cry:

**Comment by timoteojorge** [comment]
Is there a fix for it? I'm still facing the same problem...
