### ISSUE TITLE
Maskmoney should accept single digit after dot

### ISSUE THREAD

**Issue by brodock** [plentz/jquery-maskmoney#114]
When using Maskmoney with ruby BigDecimal, a integer value will be converted to something like that: '150.0' instead of '150.00', which when loaded will be rendered as "15,00".

Here are some more cases:

'150.10' => '150.1' # this one will became "15,01" on maskmoney
'150.15' => '150.15' # thats fine!

This conversion happens on the ORM (active_record) and it's not pratical to be converted to something more friendly to maskmoney, so I'm asking if it's ok to deal with this edge case?

**Comment by plentz** [comment]
@brodock I'm closing this one since #124 has a lot more people following and it's the same problem. Keep an eye there and thanks again for the report :)
