### ISSUE TITLE
Setter sets wrong value if precision: 0

### ISSUE THREAD

**Issue by tkes** [plentz/jquery-maskmoney#117]
> .maskMoney('mask') apply the mask to your input. This method can work as a setter as well, if you pass a value to it, like this .maskMoney('mask', 1999.99) 

If precision is set to 0, the setter writes a wrong value into the field (version 3.0.2).

> jQuery( '.my-field' ).maskMoney({ precision: 0 }).maskMoney( 'mask', 1000 );

This writes 10,000 into the field, instead of 1,000

http://jsfiddle.net/fC5Ar/1/

PS. I can't select the value in the field with the mouse, or click in the middle of the value, why not?

*Edit:* Went back to 2.1.2 now, both problems are solved there.

**Comment by plentz** [comment]
sorry for taking so long to reply guys. I've fixed it in master, but I want to fix a few more problems that I've found and already created the test cases. If someone want to help, here's these two tests are failling https://travis-ci.org/plentz/jquery-maskmoney (they're related). Once I've fixed those two, I will do a release and notify you :)

**Comment by ogt00l** [comment]
Wondering when this is likely to be released?
