### ISSUE TITLE
data-options for each input does not work

### ISSUE THREAD

**Issue by michail1982** [plentz/jquery-maskmoney#120]
html
```html
<input type="text" name="foo" value="0"  data-thousands="" data-precision="2" class="form-control currency" />
<input type="text" name="bar" value="0"  data-thousands=";" data-precision="1" class="form-control currency" />
```
js 
```js
$(".currency").maskMoney();
```
expect: different thousands separator & precision
get: both fields has thousands ";" & precision="1" 

proof http://jsfiddle.net/J2pqf/

**Comment by plentz** [comment]
done :)

it will be released soon ;)

**Comment by rafaelbasso** [comment]
Olá, plentz!
Primeiro, parabéns pelo excelente pluggin, já me salvou de várias!
Segundo, eu sei que o tópico está fechado, mas precisei usar 10 inputs diferentes, com quantidades de casas decimais que podem variar, e o comportamento errado voltou a acontecer. 
A versão é a última - o que eu estou fazendo errado?

Desde já, obrigado!

**Comment by adrianoresende** [comment]
Have 5 inputs with precision different and don't work.
`*  jquery-maskmoney - v3.0.2`
`$('input.price').maskMoney();`
