### ISSUE TITLE
Adding suffix breaks the mask on initial value

### ISSUE THREAD

**Issue by kartik-v** [plentz/jquery-maskmoney#131]
If you set a `suffix` then the input is not formatted correctly. For example `<input type="text" value="20316.22">`  with a suffix as say `'  c'` is displayed on initialization wrongly as: `203.16 c`

You call mask initially as
```
$('input').maskMoney('mask', 20316.22);
```

**Comment by plentz** [comment]
I'm working on a new release, but this bug is fixed in master already :)

**Comment by kartik-v** [comment]
Thanks for the update. The fix partially works. It fails if the decimal point ends with zero. Let me explain:

```js
var $input = $("#input1");
$input.maskMoney({suffix: " €"});
// the following correctly converts to 20,316.22 € 
$input.maskMoney("mask", 20316.22);

// the following wrongly converts to 2,031.62 € 
$input.maskMoney("mask", 20316.20);
```

**Comment by plentz** [comment]
@kartik-v yep. actually, the bug you reported is fixed. adding a zero to the end just make us hit another one(one that I'm working on ;) )
