### ISSUE TITLE
Mask Money not masking when input value is set programatically.

### ISSUE THREAD

**Issue by Duder-onomy** [plentz/jquery-maskmoney#142]
Here is a simple JS fiddle to demonstrate: 

http://jsfiddle.net/us6589rk/3/

Notice that the input lists as `5`. But if you gain focus, then blur, it fixes it. 

This might be related to issue #122 

I will take some time tonight to see if I can fix for you.

**Comment by p0vidl0** [comment]
Its work fine in my code:
```javascript
var newValue = 123;
$('input#apartment-pricetotal').val(newValue );
$('input#apartment-pricetotal-disp').val(newValue ).trigger('mask.maskMoney');
```
is any other more beautiful methods?

**Comment by viewbrasil** [comment]
Best Solution:

```
$('.maskMoney').maskMoney({allowNegative: false, thousands:'.', decimal:','});

$('.maskMoney').each(function(){ // function to apply mask on load!
    $(this).maskMoney('mask', $(this).val());
})
```

**Comment by Atmiya735** [comment]
We can do this by below solution
https://jsfiddle.net/atmiya/uy85fnt8/1/

**Comment by brunogringo** [comment]
Hi, put inside single brackets, worked for me!

Ex:   $("#field").maskMoney('mask', '98,94');

**Comment by Erasmojf** [comment]
$("#moneyValue").maskMoney({
            thousands: '.', decimal: ',',
            allowZero: true, affixesStay: true, prefix: " R$ 0,00 "

**Comment by gvnnunes** [comment]
> We can do this by below solution https://jsfiddle.net/atmiya/uy85fnt8/1/

This is what i needed. Just an advice, i added $('#element').blur() right after $('#element').focus() to get the best solution.

**Comment by gvnnunes** [comment]
> We can do this by below solution https://jsfiddle.net/atmiya/uy85fnt8/1/

This is what i needed. Just an advice, i added `$('#element').blur()` right after `$('#element').focus()` to get the best solution.

**Comment by pransktersnap** [comment]
Hello everyone, I find a proper solution for this case;

my code;
```
$("#product_price").maskMoney({thousands:'.', decimal:',', affixesStay: true});
$('#product_price').maskMoney('mask');
```

https://plentz.github.io/jquery-maskmoney/

**Comment by LucasHayashi** [comment]
```
	$(".brl").maskMoney({
		allowNegative: false,
		thousands: ".",
		decimal: ",",
		affixesStay: false,
		reverse: true,
	}).maskMoney('mask');
```
