### ISSUE TITLE
update config to allow removal of thousands separator

### ISSUE THREAD

**Issue by gbass84** [plentz/jquery-maskmoney#145]
This was trivial to do.  I did a pull/merge, but it failed CI bc I used a == instead of ===, while the code used a !settings.property.  I changed it to follow the code pattern, so I guess I'll do a second merge request for that....

I haven't worked on many projects on gitHub so I apologize if it's a little clunky on my side.  

Was there a was to submit to CI prior to initiating a merge request?

**Comment by plentz** [comment]
you already can do that. just use `$("#fieldId").maskMoney({thousands:''})` :)

**Comment by plentz** [comment]
ps: sorry for taking so long to reply
