### ISSUE TITLE
Initially fields can't have prefixes or sufix

### ISSUE THREAD

**Issue by dzona** [plentz/jquery-maskmoney#152]
if I have set prefix or suffix, on page load (when ``maskMoney`` has been attached to fields) I can't "make" suffixes or prefixes appear in fields, even though I get properly formatted number. If I set focus to field, and remove it, prefixes stays in fields (in case of ``affixesStay`` option set to ``true``), but on init..don't...

**Comment by plentz** [comment]
@dzona you can do that by triggering the mask event by hand. something like this

```javascript
$("#yourField").maskMoney('mask');
```

ps: sorry for taking so long to reply.
