### ISSUE TITLE
How to set empty when value is zero?

### ISSUE THREAD

**Issue by rochapablo** [plentz/jquery-maskmoney#154]
Hi everyone.

I have the input where start with value 0.00, and I need that the mask set the value to empty. I've been take a look at the others issues, but nothing worked. Here's what I tried:

``` javascript
{ defaultZero: '', allowZero: true }
```

``` javascript
{ defaultZero: false, allowZero: false }
```

Any idea?

**Comment by plentz** [comment]
duplicated

**Comment by plentz** [comment]
@rochapablo please, keep an eye on #110 :)

**Comment by plentz** [comment]
ps: sorry for taking so long to reply
