### ISSUE TITLE
In edit field, wrong position

### ISSUE THREAD

**Issue by adrianoresende** [plentz/jquery-maskmoney#170]
When someone select number in middle field to edit, after change, new number is set in last position.
For UX this is wrong, people get angry.
The correct is don't change position.

Ex: Change 1 to 2 (i select in 1 and press number 2)
Now:
1,000.00 ---> 10,000.02
Correct:
1,000.00 --> 2,000.00

**Comment by plentz** [comment]
duplicates #111
