### ISSUE TITLE
Inputs that have an initial starting value

### ISSUE THREAD

**Issue by grapho** [plentz/jquery-maskmoney#171]
I'm having some issues using this plugin with data-bound inputs.

Number one is that the mask does not apply to the input by default.

Number two is that when the mask is triggered after the fact, the decimals are not applied correctly.  A value of 1000  becomes 10.00. 

I would like the mask respect values that do _not_ include decimals initially, and only then start adding decimals going forward.. but i do not know if that is possible, the way the code is set up?

**Comment by victorasantos10** [comment]
UP

Same problem.

**Comment by FagnerMartinsBrack** [comment]
Temporary undocumented workaround.

When initializing the mask you manually trigger any of the events used to trigger the mask:

```javascript
element.maskMoney().trigger( "mask.maskMoney" );
```

**Comment by jpSimkins** [comment]
See https://github.com/plentz/jquery-maskmoney/pull/107

**Comment by FagnerMartinsBrack** [comment]
I created a fiddle with the problem two and a separate issue: http://jsfiddle.net/2kfzyb0b/

**Comment by uhtred** [comment]
Any ideas?
Same problem here: https://jsfiddle.net/5vov1nf0/

**Comment by jorool** [comment]
Same here!

I'm working around with
```
$('#myInput').maskMoney('mask', $scope.myValue);
```

But this sucks!

Any news about it?

**Comment by plentz** [comment]
Thanks for the reports guys (and sorry for taking so long to reply). Problem number one isn't really a problem. Maskmoney doesn't mask input values automatically onload right now(#161). For the problem two, the issue opened by @FagnerMartinsBrack (#174) is more specific and I will leave that one open :)
