### ISSUE TITLE
set precision to 0 ?

### ISSUE THREAD

**Issue by duynguyen0511** [plentz/jquery-maskmoney#177]
When I set the 'precision' to 0, the plugin set precision to 3. 

I enter

* 1 -> plugin translates to 0.1
* 12 -> plugin translates to 0.12
* 123 -> plugin translates to 0.123
* 1234 -> plugin translates to 1.123

Of course, the '.' separator is disabled

**Comment by ilovezy** [comment]
I got this problem too, so do I have to press 100 to ge 1.00 everytime by default, is this a bug?

**Comment by duynguyen0511** [comment]
@ilovezy by default , the precision is set to 2, so it makes sense that when you enter 100, it is 1.00

**Comment by heanluen** [comment]
Same problem here.

**Comment by plentz** [comment]
@duynguyen0511 @ilovezy @heanluen thanks for the report guys. It's already reported in #123. Keep an eye(subscribe) there :)
