### ISSUE TITLE
Is there a way to not allow zero placeholder?

### ISSUE THREAD

**Issue by jlionheart** [plentz/jquery-maskmoney#186]
Hello, thanks for the plugin. It's awesome.
I was searching the issues I could not found what I want so I decided to open a new one.

When I apply a mask for a field. When it gains focus while empty, the plugin automatically fills it with "0.00".
Is there a way to disable this behavior? I mean, leave the field empty stead of the "0.00"?

Thanks.

**Comment by plentz** [comment]
@jlionheart there's a reason for you want to do that?

**Comment by jlionheart** [comment]
I currently have a field which zero is not a valid value and I can fix that with the property allowZero set to false. But since it's not valid, displaying zero to the user seems to have no sense. It's more like a UI/UX matter.
Also, if you really plan to add this feature, it would be nice if it work with allowZero set to true as well and that it respect such behavior while the user is typing. if I try to erase the field using "backspace" key, the plugin does not allow to completely make it empty, leaving it as "0,00" stead.
I guess "allowEmpty" is a good name.

Best regards.

**Comment by jpSimkins** [comment]
see: https://github.com/plentz/jquery-maskmoney/pull/110 I think this is what you want

**Comment by jlionheart** [comment]
@jpSimkins , that's exactly what I was looking for.
thank you so much!
