### ISSUE TITLE
JQUERY - Construção dinâmica de tabela só não funciona o IE9 

### ISSUE THREAD

**Issue by RiderSet** [plentz/jquery-maskmoney#192]
Pessoal,

No trecho de código abaixo, eu insiro linhas em uma tabela conforme o botão é clicado. Tudo acontece magnificamente no Chrome, mozila, etc... Mas, no "bendito" IE9: nada acontece. Dêem uma olhada:

    $.ajax({
        type: "GET",
        url: "/App/Listar",
        success: function (dadosPessoa) {
            //var valor = $("#nome").val();
            //if (valor.length == 0) {
          if (dadosPessoa.length == 0) {
                $('table').addClass('hidden');
            } else {
                $('table').removeClass('hidden');
                $('#tbody').children().remove();
                $(dadosPessoa).each(function (i) {

                    var m1 = '/Date(';
                    var m2 = ')/';
                    var dtNasc = dadosPessoa[i].DataNascimento;
                    var dataMiliSegundos = dtNasc.replace(m1.replace(m2,''),'');

                    //var dataMiliSegundos = dadosPessoa[i].DataNascimento.replace('/Date(', '').replace(')/', '');
                    var dataNascimento = new Date(parseInt(dataMiliSegundos)).toLocaleDateString();

                    var tbody = $('#tbody');

                    var tr = "<tr>";
                    tr += "<td>" + dadosPessoa[i].Id;
                    tr += "<td>" + dadosPessoa[i].Nome;
                    tr += "<td>" + dataNascimento;
                    tr += "<td>" + dadosPessoa[i].Email;

                    tr += "<td>" + "<button class='btn btn-info' onclick=Editar(" + dadosPessoa[i].Id + ")>" + "Editar";
                    tr += "<td>" + "<button class='btn btn-danger' onclick=Deletar(" + dadosPessoa[i].Id + ")>" + "Deletar";

                    tbody.append(tr);
                });
            }
        }
    });}

Alguém pode me ajudar? Grato.

**Comment by plentz** [comment]
para dúvidas, use o http://pt.stackoverflow.com/
