### ISSUE TITLE
How to send maskmoney input as double to my Spring controller?

### ISSUE THREAD

**Issue by gtludwig** [plentz/jquery-maskmoney#201]
I'm using the following format:

$("#pay").maskMoney( {
    prefix:'R$ ', // there's a blank space after $
    allowNegative: false, 
    thousands:'.', 
    decimal:',', 
    affixesStay: false
}).maskMoney('unmasked', Number($('#pay').val()));

I want to display the money units as, say, R$ 2.345,22, but I need to send it to the controller as 2345.22

How to do so?

**Comment by plentz** [comment]
can't be done right now. the field is sent as it's displayed.
