### ISSUE TITLE
Is there any validation possibility (for the unmasked number) ?

### ISSUE THREAD

**Issue by gkatsanos** [plentz/jquery-maskmoney#205]
Is it possible for the script (or with some additions) to make sure the unmasked value isn't above or below a certain number?

**Comment by melloware** [comment]
@plentz is this project dead?  There has not been much activity and there are many good pull requests for fixing items that are not being migrated into the code.  Some sort of project status would be nice.  If you no longer have time to work on the project you should consider opening up the committers to people who have submitted high quality pull requests.

**Comment by gkatsanos** [comment]
@melloware +1

**Comment by plentz** [comment]
@gkatsanos isn't possible as it's right now. if you need some kind of validation, you should write it in regular js.

**Comment by plentz** [comment]
@melloware not dead, but yes, I haven't worked on it in the past few months. I need to check some of the pull requests, but some of then break current functionality.

**Comment by plentz** [comment]
@gkatsanos I'm closing this on since it's a question and I think that this kind of validation isn't a very good fit for the core of the project - but maybe you can convince me wrong :)
