### ISSUE TITLE
start writing from the left

### ISSUE THREAD

**Issue by BlindOSX** [plentz/jquery-maskmoney#33]
When I press the first key, this refers to the last decimal. I do not want to do that. I prefer this refers to the first number from the left. Is it possible?

**Comment by kdbusiness90** [comment]
@plentz, 
I think, reverse is not working, it is incrementing the value
 please refer video
 
![moneymask](https://user-images.githubusercontent.com/7038414/36424126-488bde3a-1668-11e8-885e-12d76581c90d.gif)
