### ISSUE TITLE
Removing mask to submit form

### ISSUE THREAD

**Issue by fabianoalmeida** [plentz/jquery-maskmoney#62]
How can I do that?

I'm using this:

``` javascript
$('#field').maskMoney('destroy');
```

but this isn't working.

I'm trying avoid some error on my rails server like this

> is not a number

Is there any simple way to do that?

Thanks in advance.

**Comment by fernandodev** [comment]
basically I've done that:
```javascript
  $("#form-id").submit(function(){
    var value = $('#input-value-id').maskMoney('unmasked')[0];
    $('#input-value-id').val(value);
  });
```
